FROM ppbymrtk/flutter:0.1.0.web

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install curl git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev -y \